### Numpy

- It deals with n-dimensional array

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
print(a)
print(a.ndim)
print(a[1])

[1 2 3]
1
2


In [3]:
d=np.array([[2,3,4],[4,5,6],
            [6,7,8],[9,10,11]])
print(d)
print(d.ndim)
print(d[0,2])

[[ 2  3  4]
 [ 4  5  6]
 [ 6  7  8]
 [ 9 10 11]]
2
4


In [4]:
three=np.array([[[1,2,3],[4,5,6],
                [7,8,9],[0,1,2]]])
print(three)
print(three.ndim)
print(three[0,0,1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [0 1 2]]]
3
2


In [5]:
print(len(three))

1


In [6]:
zeros=np.zeros((3,3),int)
print(zeros)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [7]:
ones=np.ones((4,4),int)
print(ones)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [8]:
eye=np.eye(3,3)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
fulls=np.full((3,3),50)
print(fulls)

[[50 50 50]
 [50 50 50]
 [50 50 50]]


In [10]:
fing=np.random.randint(1,30)
print(fing)

10


In [11]:
three_dim=np.array([[[3,4,5],[5,6,7],[8,9,0]],
                   [[0,12,11],[3,4,56],[7,8,9]],
                    [[99,0,1],[2,3,4],[5,6,7]]])

print("Three-d array",three_dim)
print("shape of array",three_dim.shape)
print("dim shape",three_dim.ndim)
print("Acessing of element",three_dim[2,2,1])
print("length of array:",len(three_dim))

Three-d array [[[ 3  4  5]
  [ 5  6  7]
  [ 8  9  0]]

 [[ 0 12 11]
  [ 3  4 56]
  [ 7  8  9]]

 [[99  0  1]
  [ 2  3  4]
  [ 5  6  7]]]
shape of array (3, 3, 3)
dim shape 3
Acessing of element 6
length of array: 3


In [12]:
print("mean of array:",np.mean(three_dim))
print("Max of array:",np.max(three_dim))
print("Min of array:",np.min(three_dim))
print("median of array:",np.median(three_dim))
print("variance of array",np.var(three_dim))
print("Std of array:",np.std(three_dim))

mean of array: 10.518518518518519
Max of array: 99
Min of array: 0
median of array: 5.0
variance of array 402.9163237311385
Std of array: 20.07277568576749


In [13]:
two_dim = np.array([[1, 2, 3], [4, 5, 6], [6, 7, 8],
                    [9, 1, 2], [3, 4, 5], [5, 6,7],
                   [0, 4, 5], [5, 6, 7], [7, 8, 9]])

print(two_dim.ndim)
print(two_dim)


2
[[1 2 3]
 [4 5 6]
 [6 7 8]
 [9 1 2]
 [3 4 5]
 [5 6 7]
 [0 4 5]
 [5 6 7]
 [7 8 9]]


In [14]:
arr=np.array([1,2,3,4],dtype='f')
print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


In [15]:
arr1=np.array([2.3,3.4,5.6],dtype='i')
print(arr1)
print(arr1.dtype)

[2 3 5]
int32


In [17]:
arr2=np.array([2,3,4,5,6])
x=arr2.copy()
print(x)


[2 3 4 5 6]


In [19]:
# reshaping of arrays
arr3=np.array([1,2,3,4,5,6,7,8,9,0,11,12])
print(arr3)
y=arr3.reshape(3,4)
print(y)

[ 1  2  3  4  5  6  7  8  9  0 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9  0 11 12]]


In [22]:
z=arr3.reshape(2,3,2)
print(z)
print(z.size)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9  0]
  [11 12]]]
12


In [24]:
w=arr3.reshape(3,2,2)
print(w)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9  0]
  [11 12]]]


In [28]:
# sorting
so=np.array([[3,2,4],[6,1,7]])
print(so)
s=np.sort(so)
print(s)

[[3 2 4]
 [6 1 7]]
[[2 3 4]
 [1 6 7]]


In [30]:
#slicing
print(arr3[1:2])

[2]


In [31]:
print(z[1,1:2])

[[9 0]]


In [33]:
ar1=np.array([[2,3,4],[4,5,6]])
ar2=np.array([[1,2,3],[5,6,7]])
print(ar1+ar2)
print(ar1-ar2)
print(ar1*ar2)
print(ar1/ar2)
print(ar1%ar2)

[[ 3  5  7]
 [ 9 11 13]]
[[ 1  1  1]
 [-1 -1 -1]]
[[ 2  6 12]
 [20 30 42]]
[[2.         1.5        1.33333333]
 [0.8        0.83333333 0.85714286]]
[[0 1 1]
 [4 5 6]]
